### PR TITLE
Added support to use the full browser width.

### PR DESCRIPTION
**Pull request by warren5236**

### CODE REVIEW

**Comment by fluttert** [comment]
This was exactly what i was looking for :)
Thank you!!

**Comment by jamiebuilds** [comment]
+1: Although I'd change the class to `.container-fluid` rather than applying it to the parent see [Bootstrap](http://twitter.github.com/bootstrap/scaffolding.html#fluidGridSystem)

**Comment by warren5236** [comment]
I like the idea of the `.visible-*` and `hidden-*` classes too.  :-)

**Comment by jamiebuilds** [comment]
I've been merging a bunch of these changes into one commit and improving them where I can, @dhgamache doesn't seem to have the time to go through these but their all important

**Comment by dhg** [comment]
Hey all - Apologies on not having replied to this PR in a timely fashion. Skeleton was inactive for a couple years and wasn't getting the love it needed, but now I'm committed to continuing active development and will keep stuff up to date. 

In reference to the PR, it's no longer relevant since the release of 2.0 since the new grid is fluid. That said, the structure of the grid is still a little different. If anyone in this thread is still using Skeleton or willing to give the new version a try, I'd be happy to take on feedback. 

As for the hiding/showing classes for different viewports. That has a discussion here (though it looks like I won't be adding it): https://github.com/dhg/Skeleton/issues/199

**Pull request closed without merging**
