### PR TITLE
Add 24 column version

### PR DESCRIPTION
**Pull request by lyleunderwood**
My girlfriend started using Skeleton before she realized it was not a 24 column grid (don't ask). I just went ahead and pulled the measurements from the 24 version of 960.gs, so it should match that. Might as well see if anybody here is interested.

### CODE REVIEW

**Comment by jamiebuilds** [comment]
I'm a fan. However I think they should be separated I don't see a reason for a developer to want both

**Comment by lyleunderwood** [comment]
I don't disagree.

**Comment by ghost** [comment]
Yeah, I think a 12 and 24 column version would be great ("Skeleton 12" and "Skeleton 24"?).

**Comment by surda** [comment]
inspired custom css generator as http://grids.heroku.com/?

**Comment by jamiebuilds** [comment]
@surda I think a better solution would to use a preprocessor based grid system if skeleton were to go in that direction. I also think that there should be a discussion on the way the grid system is structured to make sure that it is agreed upon, I'm currently not a fan of the class names for example.

**Comment by surda** [comment]
I agree

**Comment by rakelley** [comment]
If you want to tinker with a preprocessor version, I've already made one of the default grid at [SCSSkeleton](https://github.com/rakelley/SCSSkeleton).  Adding new widths or new column amounts should be fairly simple.

**Comment by dhg** [comment]
Hey all - 
Love seeing extensions of Skeleton. Just released v2.0 which moved Skeleton to a 12 column grid, but still not the requested 24. It's not something I want to include as part of the core, but, I'm working on a way to showcase extensions and sites created with Skeleton v2.0. I will follow up once I have that outlet.

As for a preprocessor version, there's been a lot of talk around the subject and discussion of a psuedo-official fork. Nothing in concrete, but will notify everyone here if/when it happens.

Thanks so much for the PR and completely my fault for not addressing it in a timely fashion. Skeleton is back under active development after a nearly 2 year hiatus. I apologize and really appreciate the input and promise to keep up with any future issues!

**Pull request closed without merging**
