### PR TITLE
Styling input type=tel elements

### PR DESCRIPTION
**Pull request by mileszs**
Hello, sir! 

Thank you for Skeleton. I've really enjoyed using it these past few weeks. Today I noticed that input elements of the type "tel" are not styled the same as text, email, and password input elements. It is likely that the tel type is used much more infrequently, but either Ruby on Rails 3.2, or the form builder library I am using in this project, generated an input[type="tel"] for a field called "phone", which makes good sense ultimately. I thought I'd add in the two lines it would take to get them styled similarly.

Thanks again!

### CODE REVIEW

**Comment by matthewkimber** [comment]
I second this HTML5 input styling. However, it would be great to include all input types defined by the W3C (i.e. number, tel, email, url, datetime, date, week, time, etc. - http://www.w3.org/TR/html5/the-input-element.html).

**Comment by mileszs** [comment]
As far as I can tell, only a subset of those listed are actually text fields, which is the target of this commit. In particular: tel, url, email, password, number, and (maybe) search. The others are different types of controls, and thus shouldn't be styled the same. Would you agree?

In any case, I'll add to the style to address the others. Hopefully we can get this pulled in to the main branch!

**Comment by gilluminate** [comment]
+1 from me. I noticed the same thing in an attept to add a type="tel" field to my project today.

**Comment by dhg** [comment]
This is all great feedback and is going to get incorporated in the next Skeleton point release. I'm closing this issue (even though it's the original) since the code is out of date based on v2.0 release. 

Look here for current discussion (though I'm definitely adding for next point release): https://github.com/dhg/Skeleton/issues/205

Thanks all!

**Pull request closed without merging**
