### PR TITLE
No need to prevent the users from zooming.

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by jamiebuilds** [comment]
Form inputs will zoom on focus if zooming is enabled, there are javascript workarounds for this, but for skeleton's purposes this is the best option.

**Comment by p01** [comment]
Sorry, what is the best option in your opinion ? To have or remove the  `maximum-scale=1` ?

**Comment by jamiebuilds** [comment]
To have it.

When you focus an input element (at least on the iPhone) the viewport zooms in the the element, which is okay for desktop websites but for responsive sites it actually makes it harder to use. The only built in way  to stop this is disabling zoom. There also is the issue of the site zooming in on rotate which serves no real purpose. 

There is a jQuery javascript workaround for this (popularized by jQuery UI) however Skeleton should remain without javascript thus making `maximum-scale=1` the best option.

**Comment by p01** [comment]
I would say that it is a good thing that the elements requiring user input zoom in focus so that the user actually see what she typed / is typing.

What about all the other stuff that is not an input element... like the actual content of the page ?
I can't think of a good reason or any advantage to prevent the users from zooming in as they wish.

**Comment by jamiebuilds** [comment]
Because the site is already optimized for that screen size. That's the whole point of responsive design. If the user can't see what they are doing then the problem isn't zooming

**Comment by dhg** [comment]
This discussed further here (and my opinions/resolution): https://github.com/dhg/Skeleton/issues/173

Basically the meta tag was removed with v2.0 (though the point release with the update hasn't been wrapped up yet, but it's in master). 

Thanks for all the feedback here – it influenced the final decision and was informative. 

Also, thanks so much for the PR and completely my fault for not addressing it in a timely fashion. Skeleton is back under active development after a nearly 2 year hiatus. I apologize and really appreciate the input and promise to keep up with any future issues!

**Comment by p01** [comment]
I must say that getting a deaf ear, from people working with/on Skeleton, to a trivial fix for an accessibility issue was discouraging to contribute further to the project,

Thanks for eventually addressing the issue. Looking forward to new, open, development of Skeleton!

**Comment by dhg** [comment]
@p01 I hear you man. It wasn't something intentional, but rather that I disabled Github email notifications and irresponsibly never really check the issues/pulls. I appreciate your honesty and hope I don't disappoint again :)

**Pull request closed without merging**
