### PR TITLE
Bower support

### PR DESCRIPTION
**Pull request by nickserv**
## Notes
- Helps with #197 (but you'll still have to [register your package](http://bower.io/docs/creating-packages/#register)).
- You might want to change the keywords.
- normalize.css and Raleway are included in `index.html`, but aren't part dependencies of the Bower package. You might want to add `css/normalize.css` to the `main` field or add normalize.css as a dependency if you want people to always use normalize with Skeleton (you'll still need to remind users to include the CSS file though). Also, you might want to add a note that people can get Raleway from Google Fonts.

### CODE REVIEW

**Comment by nickserv** [comment]
I just noticed that the downloads on this GitHub repository have minified versions of Skeleton. You might want to add those to the Bower package if possible, though I'm not sure if they're supposed to have minified assets...

**Comment by JakeHP** [comment]
+1, this would be great.

**Comment by dhg** [comment]
@nicolasmccurdy Any idea how it would be possible to include normalize in here too since it's a hard dependency of Skeleton? Want to do it in the simplest way possible, but not sure what the best practice would be here?

**Comment by bryangarza** [comment]
There's a dependencies option that can be included in the bower.json.

**Comment by dhg** [comment]
Check out the latest comment I made here: https://github.com/dhg/Skeleton/issues/197

Basically `bower.json` is up and running in a very rudimentary way, so I'm going to close this PR, but would love if anyone looking to improve the experience would read this thread and my thoughts and then go at it!

**Comment by dhg** [comment]
Also, @nicolasmccurdy - Thanks so much for the contribution! I basically used your bower.json as the template and worked from there, but had to do some version bumping and such so couldn't just happily auto-merge. 

Thanks again for the feedback and hope this is a step in the right direction!

**Comment by nickserv** [comment]
No problem.

I recommend adding normalize as a dependency. While it is already in the repository, it's easier for someone to update their version of normalize without having to wait for Skeleton's version to be updated. Besides, Skeleton probably doesn't need any specific version of Normalize, and Bower might let you have optional dependencies.

**Pull request closed without merging**
