### PR TITLE
remove tabs. Skeleton is not a UI framework <3

### PR DESCRIPTION
**Pull request by fat**

### CODE REVIEW

**Comment by rauchg** [comment]
+100

**Comment by rauchg** [comment]
Also, no one likes tabs on the internet

**Comment by dhg** [comment]
I agree. Let's kill em. Let me get the docs update ready and I'll push this.

**Comment by rauchg** [comment]
yaaaay

**Comment by gabeins** [comment]
Maybe release tabs as a plugin or something? Idk, someone might use it.

**Pull request merged**
