### PR TITLE
Un-jQuerified tabs.

### PR DESCRIPTION
**Pull request by pinktrink**
Tabs are now in pure JS, tested in IE7, IE8, IE9, Chrome, Firefox 4, Opera, and Safari.  I don't have the the tools at the moment to test it in any mobile browsers, but seriously if it works in IE7 AND Chrome, it pretty much has to work in mobile browsers. =P

### CODE REVIEW

**Comment by pinktrink** [comment]
I'll to continue working to reduce redundancy in newer browsers, but for now, this is a great place to start.

**Comment by dhg** [comment]
WOOHOO! This is awesome. I just need to take some time to test it across mobile devices and all supported browsers quickly before I drop it into the production code with attribution. 

Thanks so much for the support and will be sure to try to do this as soon as possible (this week for sure). 

Cheers
Dave

**Comment by pinktrink** [comment]
No problem at all =P.
If there are any issues let me know and I'll see what I can do.

**Comment by pinktrink** [comment]
Works in Dolphin Browser HD for Android, Android Browser, Firefox for Android, and Safari on iPhone.

**Comment by krunkosaurus** [comment]
Just a comment here that you could include both js files in the git repo, as the jQuery / Zepto version is much smaller if you're already using the library on your site.

**Comment by pinktrink** [comment]
In case you were planning on pulling this at any point in time, I've actually noticed a problem in my JavaScript. The current code will work, it was simply a rather small logic error that I overlooked. I'll send the commit through once I've got it figured out, shouldn't be too long.

**Comment by pinktrink** [comment]
Eww, I'm definitely running into a mess adding IE6 support with this latest fix.  I can make it happen, I have a solution ready.  The question is, do you want IE6 support or not? (DUN DUN DUUUUNNN)

**Comment by dhg** [comment]
Haha, 

So I don't support IE6 and I'm pretty sure the Skeleton grid doesn't even function properly on IE6. If the pure JS tabs work cross-browser right now (less IE6) let me know, and I will seriously get to testing it tonight and publish it in the code (and actually remove jQuery from the package). 

Thanks so much for your contribution!

**Comment by pinktrink** [comment]
Yes they definitely work in IE7+ at the moment.  I'll just commit in the small logic fix.

**Comment by pinktrink** [comment]
Actually, the small logic fix is unnecessary.  This will work in IE7+, and all other browsers.

**Comment by pinktrink** [comment]
This last commit will not affect the functionality of the tabs.  There are a couple of updates though:
- I moved all of those global functions to the `Skeleton` namespace, for organization reasons
- Changed the functionality of `getElementsByClassName` to replicate the functionality of `getElementsByClassName` in modern browsers.
- Added a `filterTags` function.
- Changed around how I handled attaching events. This means that you can use `Skeleton.addListener` to attach an event handler rather than `blah[BIND_HANDLER](BIND_HANDLER_PREFIX + "event", ...`

`Skeleton.addListener` also fixes the small logic issue I was talking about. The problem was that when an event handler is attached to an element via `attachEvent`, in IE8 and below, `this` would become entirely useless, and the handler would be called in the `window` context. As well, there is no way of obtaining the proper element to force-call the handler in the proper context.
The original script I wrote would call it in the context of the element that fired the event. This is wrong because the actual context is supposed to be the element that is handling the event, not the element that fired it. It now calls it in the proper context, fixing the small logic issue I was talking about.

In the event that `addEventListener` is detected, it takes precedence over `attachHandler`.

[This link](http://www.quirksmode.org/js/events_advanced.html) will provide more information on the IE8- event handler issues.

**Comment by pinktrink** [comment]
Ok this last commit DOES affect the functionality (well, more so the layout).  I added support for multiple tabs, which means that the `id` attribute _cannot_ be used to identify tab content anymore.  I've changed it to check `class`.
A test case that I set up was this:

``` html
<!-- All three tab sets should be able to co-exist without interfering with each other. -->
<!-- This just ensures that it still works in root -->
<ul class="tabs">
    <li><a class="active" href="#simple">Simple</a></li>
    <li><a href="#lightweight">Lightweight</a></li>
    <li><a href="#mobileFriendly">Mobile</a></li>
</ul>
<ul class="tabs-content">
    <!-- Note that blahTab identifiers are now in class instead of id -->
    <li class="active simpleTab">The tabs are clean and simple unordered-list markup and basic CSS.</li>
    <li class="lightweightTab">The tabs are cross-browser, but don't need a ton of hacky CSS or markup.</li>
    <li class="mobileFriendlyTab">The tabs work like a charm even on mobile devices. If there are too many they will stack (it's not completely awesome, but still retains functionality).</li>
</ul>

<!-- This ensure that multiple tab sets wrapped in divs work. -->
<div>
    <ul class="tabs">
        <li><a class="active" href="#simple">Simple</a></li>
        <li><a href="#lightweight">Lightweight</a></li>
        <li><a href="#mobileFriendly">Mobile</a></li>
    </ul>
    <ul class="tabs-content">
        <li class="active simpleTab">The tabs are clean and simple unordered-list markup and basic CSS.</li>
        <li class="lightweightTab">The tabs are cross-browser, but don't need a ton of hacky CSS or markup.</li>
        <li class="mobileFriendlyTab">The tabs work like a charm even on mobile devices. If there are too many they will stack (it's not completely awesome, but still retains functionality).</li>
    </ul>
</div>
<div>
    <ul class="tabs">
        <li><a class="active" href="#simple">Simple</a></li>
        <li><a href="#lightweight">Lightweight</a></li>
        <li><a href="#mobileFriendly">Mobile</a></li>
    </ul>
    <ul class="tabs-content">
        <li class="active simpleTab">The tabs are clean and simple unordered-list markup and basic CSS.</li>
        <li class="lightweightTab">The tabs are cross-browser, but don't need a ton of hacky CSS or markup.</li>
        <li class="mobileFriendlyTab">The tabs work like a charm even on mobile devices. If there are too many they will stack (it's not completely awesome, but still retains functionality).</li>
    </ul>
</div>
```

There shouldn't be more than 1 tab set in the root, otherwise it will mess up.
If you wish to have multiple tab sets, just wrap them in divs.

Tested in IE 7-9, Chrome, FF and Opera

**Comment by pinktrink** [comment]
Actually, I should say, there should be no more than 1 tab set in any element, otherwise it will mess up.  Each one should have it's own div wrapped around it.

**Comment by pinktrink** [comment]
Works in Dolphin HD for Android, Android browser, Opera Mobile on Android, and Firefox on Android.

**Comment by pinktrink** [comment]
Alright, I'm starting to see where I went wrong on those last few commits, multiple tab sets were supported, just with different IDs.  I had just noticed an issue with my code, and didn't really consider that it was _only_ my code that was the issue with not being able to have multiple tab sets.  Let me know if you want it reverted, it shouldn't be that hard.
Honestly, I'm going to have to +1 reverting it back to IDs, I liked it better that way.

I definitely derped right there.

**Comment by pinktrink** [comment]
I reverted it anyways.

**Comment by pinktrink** [comment]
This last commit does change functionality, but it's not filled with derp like the last one.  (YAAAAYYY)
The tab suffix is no longer needed:

``` html
<ul class="tabs">
    <li><a class="active" href="#simple">Simple</a></li>
    <li><a href="#lightweight">Lightweight</a></li>
    <li><a href="#mobileFriendly">Mobile</a></li>
</ul>
<ul class="tabs-content">
    <li class="active" id="simple">The tabs are clean and simple unordered-list markup and basic CSS.</li>
    <li id="lightweight">The tabs are cross-browser, but don't need a ton of hacky CSS or markup.</li>
    <li id="mobileFriendly">The tabs work like a charm even on mobile devices. If there are too many they will stack (it's not completely awesome, but still retains functionality).</li>
</ul>
```

As well, I've added a new class, "hidden" which is applied to all li's in the tab-content ul by JavaScript.  This ensures that the tab-content li's are not hidden by default if the user has JavaScript disabled.

**Comment by dhg** [comment]
Listed this as an unofficial fork for Skeleton in the "Code Example" for the tabs.js on the Skeleton docs! Going to close this pull request. 

Thanks so much for all your amazing contribution and I hope you get a ton of people using your raw JS tabs!

**Comment by dhg** [comment]
Realized I didn't give great justification for keeping the jQuery version. Ultimately, it was easier to maintain the cross-browser support, I could read and work the code and it is a smaller file for those already using jQuery. Thanks again for all your contributions though!

**Pull request closed without merging**
