### PR TITLE
Added a fluid version of the grid used in skeleton.

### PR DESCRIPTION
**Pull request by WillSkates**

### CODE REVIEW

**Comment by meowsus** [comment]
Woah! Can't wait to try this out!

**Comment by ghost** [comment]
This is really great. like meowsus said, can't wait to try this out

**Comment by theShiva** [comment]
@WillSkates The Fluid Grid is just what I was looking for! Thanks for creating it!!!

Looks like @dhgamache hasn't approved your merge request yet.

So @WillSkates , if I want to use your fluid layout in the skeleton framework, is it just a matter of downloading your **"skeleton-fluid.css"** file located in the "Files Changed" section of this project => https://github.com/dhgamache/Skeleton/pull/107/files and including this **"skeleton-fluid.css"** in place of _"skeleton.css"_ in my html pages that I am crafting using responsive approach?

Please confirm when you get a moment. Thanks again!  

-- [Shiva](https://github.com/theshiva) 
[shiva.io](http://shiva.io)

**Comment by WillSkates** [comment]
@theShiva Yep, just use skeleton-fluid.css instead of skeleton.css.

**Comment by nousename** [comment]
brilliant
or copy the content and replace partials/_grid.scss if using the sass version

now involves a bit of a rewrite, but just what was needed

**Comment by nousename** [comment]
This is horribly wrong for the mobile sizes!
When on Design for a width of 480px, you have a container width of 54% 
Which gives a much too small a container !
I've changed it by me up to 92% which gives me more what i want.

**Comment by WillSkates** [comment]
nousename: updated :D

**Comment by nousename** [comment]
thanks :)
cos otherwise it was brilliant !

**Comment by nousename** [comment]
just curious - any clever ideas how to easily update the sass version ?

this is the original

// Grid
// -------------------------------------------------- //

$grid-column-width    : 40px;
$grid-gutter-width    : 20px;
$grid-total-columns   : 16;

/\* this is margin bottom from container */
$grid-baseline-height : 0px;

$grid-offset          : ($grid-column-width + $grid-gutter-width);
$grid-width           : ($grid-offset \* $grid-total-columns);

// Grid Utility
// -------------------------------------------------- //

$grid-background-column-width   : $grid-column-width;
$grid-background-gutter-width   : $grid-gutter-width;
$grid-background-total-columns  : $grid-total-columns;
$grid-background-baseline-height: $grid-baseline-height;

what have you used for percents on the column-width, abd gutter width ?

**Comment by jpillora** [comment]
:+1: nice work @WillSkates

**Comment by mpa3b** [comment]
Guys, I'm a noob in here, how can I get the fluid grid to test?

**Comment by jpillora** [comment]
When you download Skeleton, you'll see a `skeleton.css` file, that defines the fixed grid. So just swap that file with https://raw.github.com/WillSkates/Skeleton/af6542d51df33bd2ebeb07f3e7cafd633b661145/stylesheets/skeleton-fluid.css

**Comment by mpa3b** [comment]
Thank you very much! It works well! 8) Just tested it out on one of my currently developing projects.

**Comment by WillSkates** [comment]
TYVM everyone! Any further comments or issues please let me know.

**Comment by FredGithub** [comment]
Thank you very much, it's awesome :)

**Comment by danielucas** [comment]
amazing! just what i was looking for. did anyone ever put together a .scss/.sass version of this?

**Comment by mrbusche** [comment]
@danielucas You may be looking for https://github.com/nickpack/Ribs

**Comment by danielucas** [comment]
@mrbusche ahh, perfect. thank you very much.

**Comment by dhg** [comment]
This is awesome. I'm really, really sorry I didn't get to this in a timely manner. Skeleton really needed a fluid grid and now, with v2.0 dropping, it has one. I really appreciate the contribution and I'm sure it greatly benefitted the community. 

Hopefully the new grid in v2.0 is exactly what everyone was looking for, so going to close this for now, but please feel free to re-open if there are outstanding issues w/ 2.0's grid that don't satisfy the spirit of the original PR. 

FYI: Skeleton is back under active development after a nearly 2 year hiatus. I apologize and really appreciate the input and promise to keep up with any future issues!

**Pull request closed without merging**
