### PR TITLE
I've edited paddings

### PR DESCRIPTION
**Pull request by mlesniowski**
There were no right offsets so I've changed skeleton.css a bit and now there are left and right paddings. I think it is more usable now.

### CODE REVIEW

**Comment by betovarg** [comment]
Whats the difference between offset-by-... and left-by...? they have the same values. I get the right-by... but not the left paddings.

**Comment by dhg** [comment]
Hey @lesniak - 

What's the application for the padding-right here? In what case would one use these?

Thanks for contributing and look forward to hearing back from you.

**Comment by betovarg** [comment]
I have the exact same question.

**Comment by mlesniowski** [comment]
@betovarg @dhgamache It was my kiddie mistake.

**Comment by dhg** [comment]
@lesniak haha - no worries. Thanks for following up.

**Pull request closed without merging**
