### PR TITLE
single nested column(s)

### PR DESCRIPTION
**Pull request by sampi**
added .alpha.omega to remove both margins (in case of a single nested column)

### CODE REVIEW

**Comment by dhg** [comment]
Hey sampi, 

I totally understanding the purpose of your edit, but was wondering in what situation would I ever want to next a column the exact same size as it's parent? If you can think of a situation I will for sure include it!

Thanks for your contribution!

**Comment by dhg** [comment]
Closing this down cause I can't think of a situation to use a nested column that is the exact same size as its parent. Should anyone know an awesome use case, let me know and I would be more than happy to include it :)

**Comment by sampi** [comment]
alright,
i'm really busy building a new site based on your skeleton, and
sometimes i have alpha omega classes, but since you wrote to me that
there should be no case using it i realized my mistake =)
will send you the link when finished,
although it's a stripped version of your framework,
i didn't need any of the form/tab/js stuff

great work btw!

On Tue, May 24, 2011 at 11:13 PM, dhgamache
reply@reply.github.com
wrote:

**Comment by dhg** [comment]
Rock on man.

I'm excited to see what you have cooking with Skeleton! Shoot me a link for
sure and any other feedback is welcome :)

Cheers
Dave

On Tue, May 24, 2011 at 2:18 PM, sampi <
reply@reply.github.com>wrote:

> alright,
> i'm really busy building a new site based on your skeleton, and
> sometimes i have alpha omega classes, but since you wrote to me that
> there should be no case using it i realized my mistake =)
> will send you the link when finished,
> although it's a stripped version of your framework,
> i didn't need any of the form/tab/js stuff
> 
> great work btw!
> 
> On Tue, May 24, 2011 at 11:13 PM, dhgamache
> reply@reply.github.com
> wrote:
> 
> > Closing this down cause I can't think of a situation to use a nested
> > column that is the exact same size as its parent. Should anyone know an
> > awesome use case, let me know and I would be more than happy to include it
> > :)
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/dhgamache/Skeleton/pull/12#issuecomment-1231390
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dhgamache/Skeleton/pull/12#issuecomment-1231417

## 

---

David H Gamache
Interaction Designer

---

Check out my musings and work:
www.davegamache.com

---

Follow me on Twitter:
http://www.twitter.com/dhgamache

**Pull request closed without merging**
