### PR TITLE
Creates LESS Version of Skeleton

### PR DESCRIPTION
**Pull request by WhatsNewSaes**
GRID:
- Added LESS logic so that grid columns are calculated from the total
  width of the container

VARIABLES:
- Hooked up color variables to fonts, buttons, border, backgrounds

BREAKPOINTS:
- defined breakpoints by variables.

GRUNT:
- Grunt will watch the less file and any time there is a change saved it
  will compile to the css/skeleton.css file.

### CODE REVIEW

**Comment by luisrudge** [comment]
@whatsnewsaes nice! YOu did it first! Please follow discussions [here](https://github.com/dhg/Skeleton/pull/127#issuecomment-66501251) and [here](https://github.com/dhg/Skeleton/issues/183).
Can you setup aa Skeleton-less repo? I think that would be awesome and you can make a PR to the readme pointing to your less version.

**Comment by WhatsNewSaes** [comment]
Awesome! 

Currently I have it in a forked repo here. https://github.com/whatsnewsaes/LESS-version-of-skeleton. Maybe it just stays there and @dhg just links to the forked repo on his site / readme? Not totally sure what you mean about the PR / readme though...

**Comment by deeve007** [comment]
Yes, keep it there. It should be a fork or a new repo (as you have) of Skeleton, not the main repo.

**Comment by luisrudge** [comment]
@whatsnewsaes can you rename to something like "Skeleton-less"?
Then you should do a PR over the Readme file, adding your repo info like "checkout the less version on this repo"

**Comment by deeve007** [comment]
Agree with @luisrudge

**Comment by walterdavis** [comment]
boneless?

:)

Walter

**Comment by luisrudge** [comment]
Please no. Skeleton-less should be ok

**Comment by WhatsNewSaes** [comment]
@luisrudge, you go it -- #201

**Comment by Mause** [comment]
I would love boneless if only for the doctor who reference :P

**Comment by luisrudge** [comment]
awesome!

**Comment by dhg** [comment]
This is incredible. I have a hectic day, but promise I will dig into this asap and provide some feedback. I'm noodling on the best place to provide extensions/pseudo-official forks. The README might be right, but so might some place in the docs. 

I'll get back to everyone shortly!

**Comment by sondr3** [comment]
You could potentially also make an organisation for Skeleton and put the officially approved forks in it.

**Comment by luisrudge** [comment]
Yeah. I prefer that option, since the ports would be "official". But, this comes with a higher responsability for the maintainers. It HAS to be synced all the times.

**Comment by dhg** [comment]
Alright, so here's the status! I just pushed an update to the docs with a link to "extensions" under the "more" navigation. That (as with all the other thinks there), just pushes to the README on github with links/explanation about the LESS/SASS repos @whatsnewsaes put together.

For now, since I don't have time to really dig into them I'm branding them as "unofficial" releases. A "use at your own risk" situation. I would very much like to create an organization and create official LESS/SASS versions, but for now I'm focusing on just making v2.0 the best it can be. When I'm really happy with the state of 2.0 and confident it won't be changing (except for the occasional bugfix), I will take the time to really dive and and work with @whatsnewsaes to make it all official and amazing!

@whatsnewsaes - I just dropped v2.0.2 which changed the grid selectors, some index.html meta tags, and a handful of other things (see [changelog notes](https://github.com/dhg/Skeleton/releases)). If you'd be up for updating the LESS/SASS versions that would be incredible. If not, I can try to get a PR open in the next week or so (though I have a lot of other personal commitments and work so it might take a little). 

Thanks everyone! Going to close this for now since these are linked up in the docs and readme. In the future I'd like to surface these more in actual docs, but this is a good step until we have those official versions.

**Comment by luisrudge** [comment]
Awesome, @dhg! Thanks for everything!

**Comment by WhatsNewSaes** [comment]
This is great. I'll look into getting them up to date soon. Thanks @dhg!

**Pull request closed without merging**
