### PR TITLE
Converted all of the CSS to SCSS

### PR DESCRIPTION
**Pull request by nickpack**
Hi, 

Attempting to put something back considering the time Skeleton has saved me in the past.

I've taken the liberty of converting all of the CSS to SCSS and using variables and mixins to save some of the repetition, and to also allow a basic set of customisation of the out of the box framework without too much effort.

I hope you like it ;)

### CODE REVIEW

**Comment by jswebschmiede** [comment]
:+1:

**Comment by nickpack** [comment]
Just had another big push on this, Now has grunt based build scripts (csslint, cssmin etc) and a travis config.

I also fixed as many of the warnings from csslint as humanly possible, this has changed the grid CSS a fair bit but doesnt seem to have broken any BC.

**Comment by luisrudge** [comment]
Awesome work. But maybe this should go into a different repo?

**Comment by deeve007** [comment]
I agree. I would like the main repo kept as clean & simple as possible where possible.

**Comment by nickpack** [comment]
@luisrudge @deeve007 I gave up trying to get this merged, renamed it and ran it as a seperate project. I don't actually do much frontend stuff these days, so maybe someone else can take it over and maintain it :)

**Comment by dhg** [comment]
Hey all - I'm really sorry I never got to this in a timely fashion originally. I left Skeleton in terrible disrepair for a couple years and without an active developer. I'm back at it though and committed to continuing development. I released v2.0 a week or so ago and am making my way through all the old issues and PRs.

So there is definitely going to be an active version of Skeleton for SASS and LESS, but just need to figure out exactly how they will be organized. Going to close this since it was against v1.0, but here are some references for the new versions:
- The first LESS version from @whatsnewsaes: https://github.com/dhg/Skeleton/pull/194
- PR to add new repos to README from @whatsnewsaes: https://github.com/dhg/Skeleton/pull/201

**Pull request closed without merging**
