### PR TITLE
adding package.json for 'npm install'

### PR DESCRIPTION
**Pull request by mshick**
Not sure if this is of interest to you. If it is, perhaps you'd consider publishing to npm as well.

### CODE REVIEW

**Comment by sethvincent** [comment]
It would be good to reference the css file in a `style` property like this:

```
"style": "css/skeleton.css",
```

Tools like [atomify](https://github.com/atomify/atomify) / [rework-npm](https://github.com/reworkcss/rework-npm) & [npm-css](https://github.com/defunctzombie/npm-css) use the `style` property to allow requiring css similar to requiring node modules. Makes for a really great workflow, particularly when a project is already using npm for js dependencies.

**Comment by dhg** [comment]
Please pardon my ignorance around NPM. I've used NPM quite a bit, but have never prepared a project for it. I'm sure this is perfect, but let me educate myself a bit and I promise to get back to this request and merge if it makes sense for the project. 

I really appreciate the PR and the education I'm about to get along with it.

**Comment by mshick** [comment]
It's super easy. If you have a npm account you add that and npm publish. If I recall it's totally interactive and you'll be promoted to add the creds.

I'll modify the PR to add that styles section that Seth suggested, I didn't know about those tools. 

For context -- I'm sure everybody does things a little differently -- I use Gulp and LESS and inline the CSS straight from the npm installed repo using an @import statement.

**Comment by mshick** [comment]
@sethvincent I added the style prop, and looking at normalize.css realized I had a couple of props that weren't appropriate for a CSS only module.

**Comment by aeosynth** [comment]
there already is a package named `skeleton`: https://www.npmjs.com/package/skeleton. it hasn't been updated in 2 years, so you can probably take over that name: https://www.npmjs.com/policies/disputes.

edit: there is also a recently updated skeleton.css package: https://www.npmjs.com/package/skeleton.css

**Comment by mshick** [comment]
Or maybe “skeleton.css” which is similar to how normalize.css is published.

**Comment by aeosynth** [comment]
skeleton.css has also been taken - https://www.npmjs.com/package/skeleton.css

**Comment by mshick** [comment]
Doh. Missed it by… an hour??

Looks like they’re just packing up Skeleton themselves with some fs.read() to present it in the node environment. Maybe they would be interested in doing a PR against this project to add that specific functionality here? I’ll inquire...

**Comment by mshick** [comment]
@dhg any additional thoughts on this? If you don't want to get into npm no problem, I can collaborate on @KenanY's package, or something similar.

**Comment by callumacrae** [comment]
:+1:, this would be great!

**Comment by lukehorvat** [comment]
+1 for this. Would be nice to have. NPM is starting to handle more and more front-end packages.

**Comment by patrick91** [comment]
+1

**Comment by IvoPereira** [comment]
+1

**Comment by edenworky** [comment]
+1 😁

**Comment by misterhtmlcss** [comment]
@mshick  I just forked it to keep Skeleton alive. There are 48 outstanding PRs and none of the files have been updated in 2 years. 

Please feel free to come to mine and do a PR. I'm going to start maintaining it and looking for people to help me too. Are you interested? If not, just ping me your PR and I'll test and push it out within 48 hours.

Take care @mshick

**Comment by mshick** [comment]
@misterhtmlcss It wasn't a big PR and is probably out-of-date for today. Haven't been doing much with Skeleton lately, but glad you'll be working on it. Thanks!

**Pull request closed without merging**
