### PR TITLE
Added 12 Column Support

### PR DESCRIPTION
**Pull request by offshoot**
I've added 12 column support to your framework. Also on the offsets changed the padding to margin.

### CODE REVIEW

**Comment by dhg** [comment]
Hey Offshoot, 

That's awesome! I'm not going to add this to the official master branch because I built Skeleton on the 16 column grid for a lot of reasons, but I absolutely want to let people know this is available. I'm not a Git master, but is the easiest way for me to link to your pull-request on the Skeleton docs? 

This looks like awesome work and I know a ton of people are going to benefit from this, so please let me know the BEST way to let others know this alternative version exists. 

Cheers
Dave

**Comment by tbranyen** [comment]
Might be worthwhile to create a separate branch for this.  Then merge the pull request to that branch.

**Comment by krunkosaurus** [comment]
Could just link to his repo in the docs or readme.

**Comment by pinktrink** [comment]
I'd have to agree with @tbranyen on this one.  Creating a separate branch would ensure that the different versions are kept central so that people don't have to go back and forth to find different versions of it.

**Comment by johnpeele** [comment]
I concur on the separate branch suggestion. I am currently using the 12-column version on one project and the 16-column on another project.

**Comment by dhg** [comment]
Linked to this fork in the Skeleton docs! (Just click "code example" and it's the final comment in there). 

Thanks so much for your contribution!

**Pull request closed without merging**
