### PR TITLE
skeleton1024.css

### PR DESCRIPTION
**Pull request by remkobrenters**
Added 1024px support
Removed unnecessary comments
Minor bugfixes in column widths on smaller screens
Compacted the whole thing
Removed all styling (except the CSS-reset part)

### CODE REVIEW

**Comment by simonclay** [comment]
Really great thanks! 960 was beginning to look a little narrow. I think one column should be 44px not 64px though.

**Comment by optimuswebsites** [comment]
Yes, 960 is a bit narrow. I hope there will be an update will coming soon.

**Comment by remkobrenters** [comment]
@simonclay thanks for this good comment. Made a sloppy mistake there. Fixed it directly.

**Comment by dhg** [comment]
Hey all - this is awesome that you were making improvements during Skeleton's dark days of disrepair. I recently released Skeleton v2.0 and it addresses this issue...to a degree. It still defaults Skeleton to a 960 width, but as a % based grid, it can be changed with a single `max-width` property so is no longer a real issue. Going to close this for now, but please let me know if I missed anything or this issue should stand. 

Apologies on not addressing the original issue in a timely fashion. Skeleton is back under active development and won't be left unattended again.

**Pull request closed without merging**
