### PR TITLE
Adding component.json file for Bower package system

### PR DESCRIPTION
**Pull request by javifr**
Bower is as the creators ( Twitter )  say :
THE BROWSER PACKAGE MANAGER
html, css, and javascript
http://twitter.github.com/bower/

---

Under "Authoring packages" you can see that you only need to add this component.json file and once is pushed to the git repository run this command:

bower register skeleton https://github.com/dhgamache/Skeleton.git

---

This will allow anyone on bower to do a "bower search skeleton" and find this package, and install it with a "bower install skeleton".

In the meanwhile i'm installing from the url in github.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
+1

**Comment by Doppp** [comment]
@dhg, in reference to this [comment](https://news.ycombinator.com/item?id=8726785), this PR would allow for people to use Skeleton in bower.

**Comment by hortinstein** [comment]
this would be great! +1

**Comment by tlenclos** [comment]
+1

**Comment by dhg** [comment]
Hey all - I'm really sorry I never got to this in a timely fashion originally. I left Skeleton in terrible disrepair for a couple years and without an active developer. I'm back at it though and committed to continuing development. I released v2.0 a week or so ago and am making my way through all the old issues and PRs. 

Bower support is coming soon. I'm going to close this in favor of the new PR since it's relevant to v2.0, but I really appreciate the contribution. Please feel free to comment in the new thread if you want to provide feedback: https://github.com/dhg/Skeleton/pull/200

**Pull request closed without merging**
