### PR TITLE
Lots of fixes/organizing

### PR DESCRIPTION
**Pull request by jamiebuilds**

### CODE REVIEW

**Comment by catalinmiron** [comment]
dude, the way you write css is soooo **WRONG**, please learn more and come back later ! ty

**Comment by jamiebuilds** [comment]
@catalinmiron What exactly was soooo **WRONG**?

**Comment by catalinmiron** [comment]
**Spacing issues** 
- https://github.com/dhg/Skeleton/pull/105/files#diff-0cceefeb50de59721d11452298fd6c19L72
- https://github.com/dhg/Skeleton/pull/105/files#diff-0cceefeb50de59721d11452298fd6c19L81
- https://github.com/dhg/Skeleton/pull/105/files#diff-0cceefeb50de59721d11452298fd6c19L173 
- etc ....

**Inconsistency issues**
....

What you are trying to do is not actually good for the product and doesn't bring any value to the product itself. 

Or maybe.. you ~~can't~~ can answer to this question: _What value will bring to the product with this PR ?_  

Have a nice day

**Comment by jamiebuilds** [comment]
@catalinmiron lol, you're silly

You might note that the way I was spacing is actually a very common coding style of css (lining up related values vertically), and as for value I was attempting to make the source slightly more readable, something that a lot of micro-frameworks strive for. You might also note that this is all valid CSS and I didn't add or remove anything whatsoever.

Why are you so angry? I made this PR a year ago and closed it because no one seems to be maintaining this repo anymore.

**Comment by catalinmiron** [comment]
Ok :hamster: 

> You might note that the way I was spacing is actually a very common coding style of css
> as for value I was attempting to make the source slightly more readable

_PS: You don't need to reinvent the wheel dude_
_PS2: RTFM: [Github styleguide](https://github.com/styleguide/css)_

**Comment by jamiebuilds** [comment]
@catalinmiron Okay buddy

**Comment by BelMarketingDS** [comment]
Well this was an interesting and largely unnecessary pissing contest. 

@catalinmiron If you have an issue with someone's methods of writing CSS, there are more constructive ways of going about it. If you don't like what was written, feel free not to read it. 

DBSAFD = don't be such a f*cking douche

**Comment by Scribilicious** [comment]
Lol, stop hating! Let people share their ideas of improvement. That's the
whole idea of github. And if you don't like it don't force your idea upon
someone else but improve it yourself. This isn't a competition, it is all
sharing. If you don't like this concept of sharing you should be on github!

Cheers & stop spamming my mailbox!

**Comment by Scribilicious** [comment]
Shouldn't! Should not be on github! Hahaha :p

**Comment by catalinmiron** [comment]
@Scribilicious @OllieJDesign ok
@thejameskyle sorry, hope to discuss a little in private about some css styleguide if you have time for it :+1:

**Comment by jamiebuilds** [comment]
@OllieJDesign @Scribilicious I apologize for spamming you guys (as well as everyone watching this repo). Wasn't thinking about the people still watching this considering it hasn't been active in so long. I'm not a fan of flame wars, and I'm disappointed in myself for having contributed to one. Also, I apologize for yet another spam message.

Related:
my-swag

**Pull request closed without merging**
