### PR TITLE
Clean global whitespace and tab optimizations

### PR DESCRIPTION
**Pull request by krunkosaurus**
```
Tab JS optimizations:
- Use jQuery.live so that even if tabs are ajaxed in they still work.
- Don't use DOM ready since this JS file is already at the bottom of the page.
- Remove selected class only on sibling tabs.
- Don't add a selected class on selected tab if it's already there (avoid hits to the DOM).
- Avoid using $(this) a lot, and instead use a saved reference, as you're creating a new jQuery object each time.
- Use '$' in front of jQuery variables so that you know they are jQuery objects.
```

### CODE REVIEW

**Comment by dhg** [comment]
Hey - 

Thanks for the contribution and checking the code out right now. There is actually another pull request right now that is going to remove the jQuery tabs entirely and run on pure JS. This is what I eventually wanted to remove the jQuery dependency and make the Boilerplate even more universal. 

If that doesn't pan out, I will immediately consider this for a pull, but thanks so much for supporting Skeleton either way!

**Comment by krunkosaurus** [comment]
Your welcome and thanks for a fantastic CSS framework! It's been extremely helpful in my client's webapp I'm working on right now that now resizes beautifully for mobile. Will definitely give you a heads up when it's officially out.

I commented on the other pull request that since the jQuery version will probably be way smaller in file size than a raw JS version (and support elements that don't even exist yet on page load) that both plugins could potentially be included. Also perhaps app.js should be called tabs.js and tabs.jquery.js, so that as people introduce more plugins, people can pick and choose what to use. Just an idea.

**Comment by dhg** [comment]
Sadly, just double checked this code and it didn't work in IE. It did change the content, but the e.preventDefault seemed to fail and the page would jump drastically. Going to stick with the old school tabs jQuery, but if this got fixed would love to pull it in.

**Comment by krunkosaurus** [comment]
Thanks Dave. Will work on it when I have the chance.

**Pull request closed without merging**
